require(
[
'js/Soccer/SoccerBall.js',
'js/Soccer/SoccerNet.js',
'js/Soccer/SoccerPlayer.js',
'js/Soccer/SoccerTeam.js',
'js/Soccer/SoccerStrategy.js',
'js/Soccer/SoccerGame.js',
'js/SoccerSML/SoccerSMLStrategy.js',
'js/SoccerSML/SoccerSMLPlayer.js',
'js/SoccerSML/SoccerSMLGame.js'
]);