require(
[
'js/Soccer/SoccerBall.js',
'js/Soccer/SoccerNet.js',
'js/Soccer/SoccerPlayer.js',
'js/Soccer/SoccerTeam.js',
'js/Soccer/SoccerStrategy.js',
'js/Soccer/SoccerGame.js',
'js/SoccerChess/SoccerChessPlayer.js',
'js/SoccerChess/SoccerChessGame.js'
]);